name: CI
on:
  push:
    branches: [master]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    name: flutter build
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: "11.0"
      FLUTTER_VERSION: "2.8.1"
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: $JAVA_VERSION
      - name: setup flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: $FLUTTER_VERSION
      - name: create env file
        run: |
          touch .env
          echo fhir.support=false >> .env
          echo bahmni.server=https://next.mybahmni.org >> .env
          cat .env
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter build apk
