name: CI
on:
  push:
    branches: [master]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    name: flutter build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11.0'
          distribution: 'zulu'
      - name: setup flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.8.1'
      - name: create env file
        run: |
          touch .env
          echo fhir.support=false >> .env
          echo bahmni.server=https://next.mybahmni.org >> .env
          cat .env
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter build apk
